<?php

use Illuminate\Database\Seeder;
use App\User;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        User::truncate();

        $data=[

            [
                'first_name'=>'admin',
                'last_name'=>'admin',
                'email'=>'admin@admin.com',
                'username'=>'admin',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>1,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'staff',
                'last_name'=>'staff',
                'email'=>'staff@staff.com',
                'username'=>'staff',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>2,
                'address'=>'address address',
                'phone'=>'123456',
            ],
        	[
                'first_name'=>'member',
        		'last_name'=>'member',
                'email'=>'member@member.com',
        		'username'=>'member',
        		'password'=>\Hash::make('123456'),
        		'birthday'=>'1990-11-11',
        		'role_id'=>3,
        		'address'=>'address address',
        		'phone'=>'123456',
        	],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'lao1',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'lao2',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'lao3',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'lao4',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'lao5',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'ngo1',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],[
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'ngo2',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],[
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'ngo3',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'ngo4',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'ngo5',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'rua1',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'rua2',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'rua3',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'rua4',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'rua5',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'chip1',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'chip2',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'chip3',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'chip4',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'chip5',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'mem1',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'mem2',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'mem3',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'mem4',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'mem5',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'a1',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'a0',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'a3',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'liem1234',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'test',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'a',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'liem12345',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'thaithai',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],
            [
                'first_name'=>'1',
                'last_name'=>'1',
                'email'=>'1@1.com',
                'username'=>'thaihv',
                'password'=>\Hash::make('123456'),
                'birthday'=>'1990-11-11',
                'role_id'=>3,
                'address'=>'address address',
                'phone'=>'123456',
            ],

        ];

        User::insert($data);


        // Fake data
        // $faker = Faker\Factory::create();
        // foreach (range(10,30) as $index) {
        //     User::create([
        //         'first_name'=>$faker->name,
        //         'last_name'=>$faker->name,
        //         'username'=>$faker->name,
        //         'password'=>Hash::make('123456'),
        //         'email'=>$faker->email,
        //         'role_id'=>3, 
        //         ]);
        // }
    }
}
